// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Application struct {
	ID         *string     `json:"id"`
	Name       *string     `json:"name"`
	Foundation *Foundation `json:"foundation"`
	Space      []*Space    `json:"space"`
}

type Foundation struct {
	ID            *string         `json:"id"`
	Applications  []*Application  `json:"applications"`
	Organizations []*Organization `json:"organizations"`
	Spaces        []*Space        `json:"spaces"`
}

type Organization struct {
	ID         *string     `json:"id"`
	Foundation *Foundation `json:"foundation"`
	Spaces     []*Space    `json:"spaces"`
}

type Service struct {
	ID         *string     `json:"id"`
	Name       *string     `json:"name"`
	Foundation *Foundation `json:"foundation"`
}

type ServiceBinding struct {
	ID              *string          `json:"id"`
	Foundation      *Foundation      `json:"foundation"`
	Application     *Application     `json:"application"`
	ServiceInstance *ServiceInstance `json:"serviceInstance"`
}

type ServiceInstance struct {
	ID         *string     `json:"id"`
	Foundation *Foundation `json:"foundation"`
	Service    *Service    `json:"service"`
}

type Space struct {
	ID           *string        `json:"id"`
	Foundation   *Foundation    `json:"foundation"`
	Organization *Organization  `json:"organization"`
	Applications []*Application `json:"applications"`
}
